SELECT DISTINCT  SR.NAME, O.CITY
FROM SALESREPS SR
JOIN OFFICES O ON SR.REP_OFFICE = O.OFFICE
LEFT JOIN ORDERS ORD ON SR.EMPL_NUM = ORD.REP
WHERE ORD.ORDER_NUM IS NULL OR ORD.AMOUNT <= 5000
ORDER BY O.CITY;


SELECT DISTINCT O.OFFICE, O.CITY
FROM OFFICES O
JOIN SALESREPS SR ON O.OFFICE = SR.REP_OFFICE
JOIN CUSTOMERS C ON SR.EMPL_NUM = C.CUST_REP
WHERE C.CREDIT_LIMIT > 20000;



select NAME from SALESREPS
where EMPL_NUM NOT IN
(select REP
from ORDERS
where AMOUNT > 5000)
order by (select CITY
from OFFICES
where OFFICE = REP_OFFICE)

select DISTINCT OFFICE
from OFFICES
INNER JOIN SALESREPS ON OFFICES.MGR = SALESREPS.EMPL_NUM
INNER JOIN ORDERS ON SALESREPS.EMPL_NUM = ORDERS.REP
INNER JOIN CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM
WHERE CUSTOMERS.CREDIT_LIMIT > 20000