REVOKE EXECUTE ON FUNCTION calculate_total_price(DATE, DATE) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_car(NUMERIC, INT, NUMERIC, VARCHAR(20), NUMERIC, INT, MONEY, VARCHAR(200), BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE update_car(NUMERIC, NUMERIC, INT, NUMERIC, VARCHAR(20), NUMERIC, INT, VARCHAR(200), BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE delete_car(NUMERIC, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_sparepart(VARCHAR(50), NUMERIC, VARCHAR(1000), INT, MONEY, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE update_sparepart(NUMERIC, VARCHAR(50), NUMERIC, VARCHAR(1000), INT, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE delete_sparepart(NUMERIC, INT, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_customer(VARCHAR(20), VARCHAR(20), VARCHAR(20), VARCHAR(40), VARCHAR(16), VARCHAR(50), VARCHAR(100), VARCHAR(16)) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE update_customer(NUMERIC, VARCHAR(20), VARCHAR(20), VARCHAR(20), VARCHAR(40), VARCHAR(16), VARCHAR(50), VARCHAR(100), VARCHAR(16)) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE change_status_ordercar(NUMERIC, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE change_status_orderspareparts(NUMERIC, BOOLEAN) FROM PUBLIC;

REVOKE EXECUTE ON PROCEDURE add_review_from_json() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_label_model() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_car() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_sparepart() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_customer() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_available_cars() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_available_customers() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_available_spareparts() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_manager() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_orders_cars_by_manager_id(INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_orders_spare_parts_by_customer_id(INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_customer_by_phone(VARCHAR(16)) FROM PUBLIC;

REVOKE EXECUTE ON PROCEDURE add_ordercar(INT, INT, DATE, INT, BOOLEAN, VARCHAR(1000)) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_ordersparepart(INT, INT, DATE, INT, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_review(INT, DATE, INT, VARCHAR(1000)) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_servicesheet(NUMERIC, NUMERIC, DATE, NUMERIC, VARCHAR(1000), BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_servicesheet(NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_history_orders_cars(NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_history_orders_spareparts(NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_date_status(NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_date_status_spare(NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_mechanic() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_reviews() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION check_quantity_spareparts(INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_servicesheet(NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_labels() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_models_by_label(INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_cars(INT, INT, INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_spareparts(INT, INT) FROM PUBLIC;


REVOKE EXECUTE ON FUNCTION get_mechanic_by_phone(VARCHAR(16)) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_service_sheet(INT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_customer_full_names(INT) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE update_sparepart_quantity(INT, INT) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE update_service_sheet(INT, VARCHAR(1000), MONEY, BOOLEAN) FROM PUBLIC;


REVOKE EXECUTE ON PROCEDURE add_manager(VARCHAR(20), VARCHAR(20), VARCHAR(20), VARCHAR(40), VARCHAR(16)) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE delete_manager(INT) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE add_mechanic(VARCHAR(20), VARCHAR(20), VARCHAR(20), VARCHAR(40), VARCHAR(16)) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE delete_mechanic(INT) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE change_car_price(INT, MONEY) FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE change_sparepart_price(INT, MONEY) FROM PUBLIC;
