--task 1
CREATE TABLESPACE TS_BMO
DATAFILE 'TS_BMO.dbf'
SIZE 7M
AUTOEXTEND ON
NEXT 5M
MAXSIZE 30M;
--task 2
CREATE TEMPORARY TABLESPACE TS_BMO_TEMP
TEMPFILE 'TS_BMO_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON
NEXT 3M
MAXSIZE 20M;
--task 3
SELECT tablespace_name FROM dba_tablespaces;
--task 4
SELECT tablespace_name, file_name FROM dba_data_files;
--task 5
CREATE ROLE RL_BMOCORE;
GRANT CREATE SESSION TO RL_BMOCORE;
GRANT CREATE TABLE TO RL_BMOCORE;
GRANT CREATE VIEW TO RL_BMOCORE;
GRANT CREATE PROCEDURE TO RL_BMOCORE;
--task6
SELECT * FROM dba_roles WHERE role = 'RL_BMOCORE';
--task 7
SELECT * FROM dba_sys_privs WHERE grantee = 'RL_BMOCORE';
--task 8
CREATE PROFILE PF_BMOCORE LIMIT
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LOCK_TIME 1
  PASSWORD_LIFE_TIME 90
  PASSWORD_GRACE_TIME 7;
--task 9
SELECT profile FROM dba_profiles;
--task 10
SELECT * FROM dba_profiles WHERE profile = 'PF_BMOCORE';
--task 11
SELECT * FROM dba_profiles WHERE profile = 'DEFAULT';
--task 12
CREATE USER BMOCORE
  DEFAULT TABLESPACE TS_BMO
  TEMPORARY TABLESPACE TS_BMO_TEMP
  PROFILE PF_BMOCORE
  ACCOUNT UNLOCK;
grant create session to BMOCORE;
--task 13
ALTER USER BMOCORE IDENTIFIED BY NewPassword;

grant create table to BMOCORE;
--task 16
ALTER USER BMOCORE QUOTA 2M ON TS_BMO;
INSERT INTO XXX_T (column1, column2) VALUES ('Value1', 123);
CREATE TABLE XXX_T (
  column1 VARCHAR2(50),
  column2 NUMBER
);
--18
ALTER TABLESPACE TS_BMO OFFLINE;
--20
ALTER TABLESPACE TS_BMO ONLINE;
SELECT * FROM XXX_T;