SELECT AUDITORIUM.AUDITORIUM_TYPE AS ÒÈÏ,
MAX(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÌÀÊÑ,
MIN(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÌÈÍ,
AVG(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÑÐÅÄÍßß,
SUM(AUDITORIUM.AUDITORIUM_CAPACITY) AS ÑÓÌÌÀÐÍÀß,
COUNT(AUDITORIUM.AUDITORIUM_TYPE) AS ÊÎËÈ×ÅÑÒÂÎ
FROM AUDITORIUM JOIN AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM.AUDITORIUM_TYPE

SELECT * FROM PROGRESS
SELECT NOTE AS ÎÖÅÍÊÀ, COUNT(NOTE) AS ÊÎËÈ×ÅÑÒÂÎ
FROM
  (SELECT CASE
      WHEN PROGRESS.NOTE BETWEEN 9 AND 10 THEN '9-10'
      WHEN PROGRESS.NOTE BETWEEN 7 AND 8 THEN '7-8'
      WHEN PROGRESS.NOTE BETWEEN 5 AND 6 THEN '5-6'
      ELSE '4'
    END AS NOTE FROM PROGRESS) AS A
GROUP BY NOTE ORDER BY NOTE DESC;

SELECT FACULTY.FACULTY_NAME AS ÔÀÊÓËÜÒÅÒ, GROUPS.PROFESSION AS ÏÐÎÔÅÑÑÈß,
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2) AS ÎÖÅÍÊÀ 
FROM PROGRESS JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
GROUP BY FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.NOTE 
ORDER BY PROGRESS.NOTE DESC

SELECT FACULTY.FACULTY_NAME AS ÔÀÊÓËÜÒÅÒ, GROUPS.PROFESSION AS ÏÐÎÔÅÑÑÈß,
ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT(4))),2) AS ÎÊÐÓÃËÅÍÍÎÅ 
FROM PROGRESS JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
WHERE PROGRESS.SUBJECT = 'ÁÄ' OR PROGRESS.SUBJECT = 'ÎÀèÏ'
GROUP BY FACULTY.FACULTY_NAME, GROUPS.PROFESSION, PROGRESS.NOTE
ORDER BY PROGRESS.NOTE DESC

SELECT PROGRESS.SUBJECT AS ÏÐÅÄÌÅÒ, FACULTY.FACULTY AS ÔÀÊÓËÜÒÅÒ, GROUPS.PROFESSION AS ÏÐÎÔÅÑÑÈß, 
AVG(PROGRESS.NOTE) AS ÑÐÅÄÍÈÅ
FROM PROGRESS JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
WHERE FACULTY.FACULTY = 'ÒÎÂ' 
GROUP BY PROGRESS.SUBJECT, GROUPS.PROFESSION, FACULTY.FACULTY

SELECT PROGRESS.SUBJECT AS ÏÐÅÄÌÅÒ, COUNT(IDSTUDENT) AS ÊÎËÈ×ÅÑÒÂÎ
FROM PROGRESS
WHERE PROGRESS.NOTE = 8 OR PROGRESS.NOTE = 9
GROUP BY PROGRESS.SUBJECT
HAVING  COUNT(IDSTUDENT) > 0
ORDER BY PROGRESS.SUBJECT DESC;