use UNIVER
select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM_TYPE.AUDITORIUM_TYPE
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE =  AUDITORIUM_TYPE.AUDITORIUM_TYPE;


select AUDITORIUM, AUDITORIUM.AUDITORIUM_TYPE , AUDITORIUM_TYPENAME , AUDITORIUM_NAME  
from AUDITORIUM inner join AUDITORIUM_TYPE 
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
and AUDITORIUM_TYPENAME like '%компьютер%';

SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, GROUPS.PROFESSION, SUBJECT.SUBJECT_NAME, STUDENT.NAME, 
       CASE
           WHEN PROGRESS.NOTE = 6 THEN 'шесть'
           WHEN PROGRESS.NOTE = 7 THEN 'семь'
           WHEN PROGRESS.NOTE = 8 THEN 'восемь'
       END AS ќценка
FROM PROGRESS
INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
WHERE PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY PROGRESS.NOTE DESC;

select PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME, '***')
from PULPIT left outer join TEACHER
on TEACHER.PULPIT = PULPIT.PULPIT

Select  PULPIT.PULPIT_NAME ,TEACHER.TEACHER_NAME 
from TEACHER 
full outer join  PULPIT   on PULPIT.PULPIT = TEACHER.PULPIT
where TEACHER.TEACHER_NAME is NULL

Select  PULPIT.PULPIT_NAME ,TEACHER.TEACHER_NAME 
from TEACHER 
full outer join  PULPIT
on PULPIT.PULPIT = TEACHER.PULPIT


Select  PULPIT.PULPIT_NAME ,TEACHER.TEACHER_NAME 
from TEACHER 
full outer join  PULPIT on PULPIT.PULPIT = TEACHER.PULPIT
where  PULPIT.PULPIT_NAME  is  NULL

Select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM  cross join AUDITORIUM_TYPE 
where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
